# Generated by Django 5.1.5 on 2025-11-28 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('owner_name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=15)),
                ('is_approved', models.BooleanField(default=False)),
            ],
        ),
    ]
