# Generated by Django 5.1.5 on 2025-01-29 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookslot',
            name='time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookslots', to='turf.time'),
        ),
        migrations.AddField(
            model_name='bookslot',
            name='turf_booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookslots', to='turf.turfbooking'),
        ),
    ]
