# Generated by Django 5.1.5 on 2025-03-27 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turf', '0002_bookslot_time_bookslot_turf_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookslot',
            name='week',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='time',
            name='week',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='turfbooked',
            name='slots',
            field=models.JSONField(default=list),
        ),
    ]
