# Generated by Django 5.1.5 on 2025-03-27 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turf', '0003_alter_bookslot_week_alter_time_week_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookslot',
            name='week',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='time',
            name='week',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='turfbooked',
            name='slots',
            field=models.TextField(),
        ),
    ]
